//
//  AppNotification.h
//  housefinder
//
//  Created by zhengying on 3/4/13.
//  Copyright (c) 2013 zhengying. All rights reserved.
//

#ifndef housefinder_AppNotification_h
#define housefinder_AppNotification_h


#define NOTIFY_MESSAGE_AUTH_LOGIN_SUCCESS @"NOTIFY_MESSAGE_AUTH_LOGIN_SUCCESS"
#define NOTIFY_MESSAGE_AUTH_LOGIN_FAILD @"NOTIFY_MESSAGE_AUTH_LOGIN_FAILD"
#define NOTIFY_MESSAGE_GET_MAIN_INFO @"NOTIFY_MESSAGE_GET_MAIN_INFO"
#define NOTIFY_MESSAGE_GET_SYSCONFIG_INFO @"NOTIFY_MESSAGE_GET_SYSCONFIG_INFO"
#define NOTIFY_MESSAGE_SWITCH_VIEW @"NOTIFY_MESSAGE_SWITCH_VIEW"
#define NOTIFY_MESSAGE_UPDATE_PROFILE_INFO @"NOTIFY_MESSAGE_UPDATE_PROFILE_INFO"
#define NOTIFY_MESSAGE_UPDATE_TASK_STATUS @"NOTIFY_MESSAGE_UPDATE_TASK_STATUS"
#define NOTIFY_MESSAGE_WEBSOCKET_COMING @"NOTIFY_MESSAGE_WEBSOCKET_COMING"
#define NOTIFY_MESSAGE_UPDATE_LEADBOARD @"NOTIFY_MESSAGE_UPDATE_LEADBOARD"
#define NOTIFY_MESSAGE_LOGOUT_SUCCESS @"NOTIFY_MESSAGE_LOGOUT_SUCCESS"
#define NOTIFY_MESSAGE_PROGRAM_RESIGNACTIVE @"NOTIFY_MESSAGE_PROGRAM_RESIGNACTIVE"
#define NOTIFY_MESSAGE_UPDATE_LOGIN_INFO @"NOTIFY_MESSAGE_UPDATE_LOGIN_INFO"
#define NOTIFY_MESSAGE_UPDATE_PK_TIMES @"NOTIFY_MESSAGE_UPDATE_PK_TIMES"
#define NOTIFY_MESSAGE_UPDATE_ARTICLE_AFTER_EVENT @"NOTIFY_MESSAGE_UPDATE_ARTICLE_AFTER_EVENT"

#define NOTIFY_MESSAGE_ANIMATION_STATE @"NOTIFY_MESSAGE_ANIMATION_STATE"

#define NOTIFY_MESSAGE_MSG_LIST_UPDATE @"message_list_update"
#define NOTIFY_MESSAGE_WALLET_UPDATE @"message_wallet_update"
#define NOTIFY_MESSAGE_NEW_ARTICLE_UPDATE @"NOTIFY_MESSAGE_NEW_ARTICLE_UPDATE"
#define NOTIFY_MESSAGE_UPDATE_PROCESS_TO_WATCH @"NOTIFY_MESSAGE_UPDATE_PROCESS_TO_WATCH"

#define VIEW_LOGIN_PAGE @"登录"
#define VIEW_MAIN_PAGE @"主页"
#define VIEW_SEARCH_PAGE @"发现"
#define VIEW_CONTACTS_PAGE @"联系人"
#define VIEW_ACCOUNT_PAGE @"我的"

#endif
