# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SogouYuedu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SogouYuedu
    pod 'MJExtension'
    pod 'SDWebImage'
    pod 'YTKNetwork'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'JVFloatingDrawer'
    pod 'FMDB'
    pod 'SSZipArchive'
    pod 'MBProgressHUD'

end
