# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Masonry', '~> 0.6.4'

target 'HCCountdown' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HCCountdown

end
