platform :ios, '8.0'

inhibit_all_warnings!

target 'GKAudioPlayerDemo' do
  use_frameworks!

  pod 'MobileVLCKit-unstable'
  pod 'GKNavigationBarViewController'
  pod 'YYModel'
  pod 'AFNetworking'
  pod 'GKCover'
  pod 'SDWebImage'
  pod 'Masonry'
  
#  pod 'MBProgressHUD'
  pod 'GKMessageTool'

end
