//
//  ServiceKeys.h
//  SportForumApi
//
//  Created by liyuan on 14-6-12.
//  Copyright (c) 2014年 liyuan. All rights reserved.
//

#ifndef SportClient_ServiceKeys_h
#define SportClient_ServiceKeys_h

//--- API MESSAGE KEY ---
#define IS_REQUEST_TASKS_FINISHED @"IS_REQUEST_TASKS_FINISHED"

//--- API ENUM KEY ---
#define login_email @"email"
#define login_phone @"phone"
#define login_weibo @"weibo"
#define login_nickname @"nickname"
#define login_weixin @"weixin"
#define login_usrpass @"usrpass"
#define login_guest @"guest"
#define article_text @"text"
#define article_image @"image"
#define send_type_text @"text"
#define send_type_voice @"voice"
#define send_type_image @"image"
#define send_type_video @"video"
#define event_thumb @"thumb"
#define event_chat @"chat"
#define event_article @"article"
#define article_all @"ALL"
#define article_comments @"COMMENTS"
#define article_articles @"ARTICLES"
#define sport_type_run @"run"
#define sport_type_ride @"ride"
#define sport_type_swimming @"swimming"
#define board_query_top @"TOP"
#define board_query_friend @"FRIEND"
#define board_query_user_around @"USER_AROUND"
#define actor_pro @"PRO"
#define actor_mid @"MID"
#define actor_amatrur @"AMATEUR"
#define member_friend @"FRIENDS"
#define member_attention @"ATTENTION"
#define member_fans @"FANS"
#define member_defriend @"DEFRIEND"
#define member_weibo @"WEIBO"
#define task_physique @"PHYSIQUE"
#define task_literature @"LITERATURE"
#define task_magic @"MAGIC"
#define task_normal @"NORMAL"
#define task_finish @"FINISH"
#define task_unfinish @"UNFINISH"
#define task_authentication @"AUTHENTICATION"
#define sport_Log @"SPORT_LOG"
#define sport_theory @"SPORT_THEORY"
#define equip_blog @"EQUIP_BLOG"
#define sport_life @"SPORT_LIFE"
#define product_proposal @"PRODUCT_PROPOSAL"
#define sex_male @"male"
#define sex_female @"female"
#define trade @"TRADE"
#define reward @"REWARD"
#define Image @"image"
#define NewCount @"new_count"
#define TotalCount @"total_count"
#define MsgContent @"msg_content"
#define MsgType @"msg_type"
#define Chat @"chat"
#define GroupChat @"groupchat"
#define SubScribe @"subscribe"
#define UnSubScribe @"unsubscribe"
#define Thumb @"thumb"
#define Comment @"comment"
#define Coach @"coach"
#define Trade @"tx"
#define Reward @"reward"
#define SendHeart @"sendheart"
#define ReceiveHeart @"recvheart"
#define Game_MISHI @"MISHI"
#define Game_QIXI @"QIXI"
#define Game_SPIDERMAN @"SPIDERMAN"
#define Game_XIONGCHUMO @"XIONGCHUMO"
#define Game_ZNM @"ZNM"
#define Auth_IdCard @"idcard"
#define Auth_Cert @"cert"
#define Auth_Record @"record"
#define Auth_Unverified @"unverified"
#define Auth_Verifying @"verifying"
#define Auth_Verified @"verified"
#define Auth_Refused @"refused"
#define Accept_Physique @"PHYSIQUE"
#define Accept_Literature @"LITERATURE"
#define Accept_Pk @"MAGIC"

// --- API Parameter Key ---
#define kAccessToken @"access_token"
#define kEmail @"email"
#define kPassword @"password"
#define kNikeName @"nikename"
#define kUserId @"userid"
#define kUserIds @"userids"
#define kbAttention @"bAttention"
#define kbDeFriend @"bDefriend"
#define kVerfiyCode @"verfiycode"
#define kAccountType @"account_type"
#define kAppKey @"appkey"
#define kImageId @"image_id"
#define kPicIds @"pic_ids"
#define kPicId @"pic_id"
#define kArticleId @"article_id"
#define kPageNumber @"page_number"
#define kContents @"contents"
#define kThumbStatus @"thumb_status"
#define kIsThumbed @"is_thumbed"
#define kFileData @"filedata"
#define kFileId @"fileid"
#define kFileUrl @"fileurl"
#define kImageSizeType @"image_size_type"
#define kImageUrl @"image_url"
#define kChatToId @"to_id"
#define kChatType @"type"
#define kChatContent @"content"
#define kMessageId @"message_id"
#define kFromId @"from_id"
#define kParentArticleId @"parent_article_id"
#define kArticleSegments @"article_segments"
#define kArticleTag @"article_tag"
#define kPageFirstId @"page_frist_id"
#define kPageLastId @"page_last_id"
#define kPageItemCount @"page_item_count"
#define kPageIndex @"page_index"
#define kGameScore @"game_score"
#define kArticleType @"article_type"
#define kMemberType @"member_type"
#define kGameType @"game_type"
#define kId @"id"
#define fileIds @"fids"
#define kDeviceToken @"device_token"
#define kIsEnabled @"is_enabled"
#define kIsUsed @"is_used"
#define kRecordItem @"record_item"
#define kLeaderBoardEffect @"leaderboard_effect"
#define kSelfRecordEffect @"self_record_effect"
#define kQueryType @"query_type"
#define kQueryInfo @"query_info"
#define kGroupId @"group_id"
#define kTaskId @"task_id"
#define kTaskPics @"task_pics"
#define kFrom @"from"
#define kTo @"to"
#define kValue @"value"
#define kAddr @"addr"
#define kTradeType @"trade_type"
#define kUserEquipInfo @"user_equipInfo"
#define kContacts @"contacts"
#define kPhoneNum @"phone_number"
#define kCoinValue @"coin_value"
#define kIsAttentionCircle @"IsAttentionCircle"

// --- API url ----

// Account action
#define urlAccountRegester @"account/register"
#define urlAccountRegesterV2 @"account/registerV2"
#define urlAccountLogin @"account/login"
#define urlAccountLoginV2 @"account/loginV2"
#define urlAccountImportFriends @"account/importFriends"
#define urlAccountChangePassword @"account/changePassword"
#define urlAccountCheck @"account/check"

// User action
#define urlUserLogout @"user/logout"
#define urlUserGetDailyLoginRewardInfo @"user/getDailyLoginRewardInfo"
#define urlUserGetPKPropertiesInfo @"user/getPKPropertiesInfo"
#define urlUserGetPropertiesValue @"user/getPropertiesValue"
#define urlUserGetInfo @"user/getInfo"
#define urlUserSetInfo @"user/setInfo"
#define urlUserUpdateEquipment @"user/updateEquipment"
#define urlUserSetLifePhotos @"user/setLifePhotos"
#define urlUserDelLifePhoto @"user/deleteLifePhoto"
#define urlUserSetProfileImage @"user/setProfileImage"
#define urlUserEnableAttention @"user/enableAttention"
#define urlUserEnableDefriend @"user/enableDefriend"
#define urlUserGetRelatedMembersCount @"user/getRelatedMembersCount"
#define urlUserGetRelatedMembersList @"user/getRelatedMembersList"
#define urlUserSearch @"user/search"
#define urlUserArticles @"user/articles"
#define urlUserNews @"user/new"
#define urlUserSendDeviceToken @"user/send_device_token"
#define urlUserSetPushEnable @"user/set_push_enable"
#define urlUserIsPushEnabled @"user/is_push_enabled"
#define urlUserNewGroup @"user/newGroup"
#define urlUserRecommend @"user/recommend"
#define urlImportContacts @"user/importContacts"
#define urlUserResetPassword @"user/resetPassword"
#define urlUserShareToFriends @"user/shareToFriends"
#define urlUserIsNikeNameUsed @"user/isNikeNameUsed"
#define urlUserGameResults @"user/gameResults"
#define urlUserPurchaseSuccess @"user/purchaseSuccess"
#define urlUserGetPayHistory @"user/getPayHistory"
#define urlUserLeaderBoard @"user/leaderboard"
#define urlUserAuthRequest @"user/auth/request"
#define urlUserAuthStatus @"user/auth/status"
#define urlUserAuthInfo @"user/auth/info"
#define urlUserSendHeart @"user/sendheart"
#define urlUserReceiveHeart @"user/recvheart"
#define urlUserRanks @"user/ranks"
#define urlUserIsPreSportForm @"user/isPreSportForm"
#define urlUserAction @"user/action"

// Tasks action
#define urlTasksGet @"tasks/get"
#define urlTasksGetList @"tasks/getList"
#define urlTasksGetInfo @"tasks/getInfo"
#define urlTasksExecute @"tasks/execute"
#define urlTasksResult @"tasks/result"
#define urlTasksReferrals @"tasks/referrals"
#define urlTasksShare @"tasks/share"
#define urlTasksShared @"tasks/shared"
#define urlTasksReferralPass @"tasks/referral/pass"

// Article action
#define urlArticleNew @"article/new"
#define urlArticleDelete @"article/delete"
#define urlArticleThumb @"article/thumb"
#define urlArticleGet @"article/get"
#define urlArticleIsThumbed @"article/is_thumbed"
#define urlArticleTimeLines @"article/timelines"
#define urlArticleComments @"article/comments"
#define urlArticleThumbList @"aritcle/thumbList"
#define urlArticleRewardList @"article/reward_list"
#define urlArticleNews @"article/news"
#define urlArticleRepost @"article/repost"

// Record action
#define urlRecordNew @"record/new"
#define urlRecordTimeline @"record/timeline"
#define urlLeaderBoardList @"leaderboard/list"
#define urlRecordStatistics @"record/statistics"
#define urlLeaderBoardGameList @"leaderboard/gameList"
#define urlRecordGet @"record/get"
#define urlLeaderBoardVideoList @"leaderboard/videoList"
#define urlLeaderBoardVideoInfo @"leaderboard/videoInfo"

// Event action
#define urlEventNews @"event/news"
#define urlEventNewsDetails @"event/news_details"
#define urlEventChangeStatusRead @"event/change_status_read"
#define urlEventNotices @"event/notices"

// Comment action
#define urlCommentTimeline @"comment/timeline"

// Chat action
#define urlChatSendMessage @"chat/send_message"
#define urlChatRecentChatInfos @"chat/recent_chat_infos"
#define urlChatGetList @"chat/get_list"
#define urlChatChangeStatusRead @"chat/change_status_read"
#define urlChatDeleteMessage @"chat/delete"

// File action
#define urlImageGet @"image/get"
#define urlFileUpload @"file/upload"
#define urlFileDelete @"file/delete"
#define urlFileUpToken @"file/uptoken"

//System action
#define urlSysConfig @"sys/config"

// Wallet action
#define urlWalletGet @"wallet/get"
#define urlWalletBalance @"wallet/balance"
#define urlWalletNewAdd @"wallet/newaddr"
#define urlWalletSend @"wallet/send"
#define urlWalletTxs @"wallet/txs"

#endif
