target 'DownLoadTest'  do
platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'Masonry', '~> 0.0'
pod 'JSONModel'
pod 'MBProgressHUD', '0.9'
pod 'IQKeyboardManager'
pod 'Reachability'
pod 'AutoCoding'
pod 'SWTableViewCell', '~> 0.3.7'
end
