use_frameworks!

platform :ios, '8.0'

target 'ZPScrollerScaleView_Example' do
  pod 'ZPScrollerScaleView', :path => '../'

  target 'ZPScrollerScaleView_Tests' do
    inherit! :search_paths

    
  end
end
