project 'JGTaoBaoShopping.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JGTaoBaoShopping' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JGTaoBaoShopping

  pod 'Masonry'
  pod 'MGSwipeTableCell'
  pod 'SDWebImage'

  #target 'JGTaoBaoShoppingTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

  #target 'JGTaoBaoShoppingUITests' do
    inherit! :search_paths
    # Pods for testing
 # end

end
