use_frameworks!

platform :ios, '8.0'

target 'WGBCommonAlertSheetView_Example' do
  pod 'WGBCommonAlertSheetView', :path => '../'

  target 'WGBCommonAlertSheetView_Tests' do
    inherit! :search_paths

    
  end
end
