platform :ios, '8.0'
target 'HongKZH_IOS' do
    pod 'AFNetworking', '>= 3.2.0'
    pod 'Masonry', '~> 0.6.3'
    pod 'UILabel+ContentSize', '~> 1.0.1'
    pod 'UIAlertView-Blocks', '~> 1.0'
    pod 'AlipaySDK-2.0', '~> 3.0.1.3'
    pod 'CNTreeNode', '~> 0.1.2'
    pod 'MJExtension', '~> 3.0.7'
    pod 'LCTabBarController', '~> 1.3.7'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'SDCycleScrollView', '~> 1.3'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'FMDB'
    pod 'TTTAttributedLabel'
    pod'ActionSheetPicker-3.0'
    pod'MJExtension'
    pod 'RongCloudIM/IMLib', '~> 2.8.3'
    pod 'RongCloudIM/IMKit', '~> 2.8.3'
    pod 'AMapLocation'
    pod 'LXMThirdLoginManager', '~> 1.1.0'
    pod 'CNTreeNode', '~> 0.1.2'
    pod 'LKDBHelper', '~> 2.1.6'
    pod 'Mantle', '~> 2.0.5'
    pod 'IQKeyboardManager'
    pod 'YYWebImage','~> 1.0.5'
    pod 'TZImagePickerController' 
    
end
