# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrollviewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SDWebImage', '~> 3.7'
  # Pods for ScrollviewDemo

  target 'ScrollviewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrollviewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
