# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShrinkageTB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShrinkageTB

  pod 'Masonry', '~> 1.1.0'
  
  target 'ShrinkageTBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShrinkageTBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
