language: objective-c
osx_image: xcode11.3.1

before_install:
  - env
  - locale
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail

after_success:
  - bash <(curl -s https://codecov.io/bash)
